### ISSUE TITLE
Microservice for user management (SIMPLE)

### ISSUE THREAD

**Issue by mteXD** [PRPO-skupina-08/JustPhotons#1]
A very simplistic user management API for this microservice has to be created.

API structure:
- `/user` - GET, POST
- `/user/{id}` - GET, DELETE, PUT, PATCH

Available functions:
- `createUser`
- `deleteUser`
- `changeUsername`
- `deleteUser`
- `createUser`
- `deleteUser`

**Comment by vojkoh** [comment]
`/user` --> `/users` nouns should be in plural

**Comment by vojkoh** [comment]
PATCH damo ven.
